services:
  etcd0:
    image: quay.io/coreos/etcd:v3.5.10
    container_name: etcd0
    restart: always
    ports:
      - "4001:4001"
      - "2380:2380"
      - "2379:2379"
    environment:
      NODE1: "192.168.1.132"
    volumes:
      - './etcd:/etcddata'
    command: etcd --data-dir=/etcddata --name=node1 --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls='http://0.0.0.0:2379'
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "10"

