apiVersion: v1
kind: Pod
metadata:
  name: qdrant-stack
  labels:
    app: qdrant
spec:
  containers:
  - name: qdrant
    image: docker.io/qdrant/qdrant:v1.17.0
    ports:
    - containerPort: 6333
      hostPort: 6333
    - containerPort: 6334
      hostPort: 6334
    resources:
      limits:
        memory: 5Gi
      requests:
        memory: 2Gi
    env:
    - name: QDRANT__SERVICE__API_KEY
      value: "ZWhZ03KYZlPPmEp050IVPEQd3cCRfqKd"  # 請替換
    - name: QDRANT__SERVICE__READ_ONLY_API_KEY
      value: "RxfCKM2PoMufFXIsZiDaw2a0o1GIQ894"   # 請替換
    - name: QDRANT__STORAGE__ON_DISK_PAYLOAD
      value: "true"
    - name: QDRANT__STORAGE__MEMMAP_THRESHOLD_KB
      value: "512"
    - name: QDRANT__SERVICE__MAX_REQUEST_SIZE_MB
      value: "32"
    - name: QDRANT__SERVICE__GRPC_PORT
      value: "6334"
    - name: QDRANT__COLLECTION__DEFAULT_HNSW_EF_CONSTRUCT
      value: "200"
    - name: QDRANT__COLLECTION__DEFAULT_HNSW_M
      value: "16"
    volumeMounts:
    - mountPath: /qdrant/storage
      name: qdrant-data
    securityContext:
      capabilities:
        add: ["SYS_RESOURCE"] # 有助於 Ulimit 生效
  volumes:
  - name: qdrant-data
    hostPath:
      path: ./storage # Podman 會自動對應到當前目錄
      type: DirectoryOrCreate
