services:
  # EMQX Core 節點 1
  emqx-core-1:
    image: emqx/emqx:5.3.2
    container_name: emqx-core-1
    hostname: emqx-core-1.emqx.local
    environment:
      - EMQX_NODE_NAME=emqx@emqx-core-1.emqx.local
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=[emqx@emqx-core-1.emqx.local,emqx@emqx-core-2.emqx.local]
      - EMQX_NODE__ROLE=core
    # ports:
    #   - "1883:1883"     # MQTT
    #   - "8083:8083"     # MQTT over WebSocket
    #   - "8084:8084"     # MQTT over SSL
    #   - "8883:8883"     # MQTT over SSL
    #   - "18083:18083"   # MQTT dashboard
    networks:
      emqx-network:
        aliases:
          - emqx-core-1
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5

  # EMQX Core 節點 2
  emqx-core-2:
    image: emqx/emqx:5.3.2
    container_name: emqx-core-2
    hostname: emqx-core-2.emqx.local
    environment:
      - EMQX_NODE_NAME=emqx@emqx-core-2.emqx.local
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=[emqx@emqx-core-1.emqx.local,emqx@emqx-core-2.emqx.local]
      - EMQX_NODE__ROLE=core
    # ports:
    #   - "1883:1883"     # MQTT
    #   - "8083:8083"     # MQTT over WebSocket
    #   - "8084:8084"     # MQTT over SSL
    #   - "8883:8883"     # MQTT over SSL
    #   - "18083:18083"   # MQTT dashboard
    networks:
      emqx-network:
        aliases:
          - emqx-core-2
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5

  # EMQX Replicant 節點 1
  emqx-replicant-1:
    image: emqx/emqx:5.3.2
    container_name: emqx-replicant-1
    hostname: emqx-replicant-1.emqx.local
    environment:
      - EMQX_NODE_NAME=emqx@emqx-replicant-1.emqx.local
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=[emqx@emqx-core-1.emqx.local,emqx@emqx-core-2.emqx.local]
      - EMQX_NODE__ROLE=replicant
    # ports:
    #   - "1883:1883"     # MQTT
    #   - "8083:8083"     # MQTT over WebSocket
    #   - "8084:8084"     # MQTT over SSL
    #   - "8883:8883"     # MQTT over SSL
    #   - "18083:18083"   # MQTT dashboard
    networks:
      emqx-network:
        aliases:
          - emqx-replicant-1
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5

  # EMQX Replicant 節點 2
  emqx-replicant-2:
    image: emqx/emqx:5.3.2
    container_name: emqx-replicant-2
    hostname: emqx-replicant-2.emqx.local
    environment:
      - EMQX_NODE_NAME=emqx@emqx-replicant-2.emqx.local
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=[emqx@emqx-core-1.emqx.local,emqx@emqx-core-2.emqx.local]
      - EMQX_NODE__ROLE=replicant
    # ports:
    #   - "1883:1883"     # MQTT
    #   - "8083:8083"     # MQTT over WebSocket
    #   - "8084:8084"     # MQTT over SSL
    #   - "8883:8883"     # MQTT over SSL
    #   - "18083:18083"   # MQTT dashboard
    networks:
      emqx-network:
        aliases:
          - emqx-replicant-2
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5

  nginx-lb:
    image: nginx:1.28.0-alpine3.21
    container_name: emqx-nginx-lb
    ports:
      - "1883:1883"
      - "18083:18083"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - emqx-network
    depends_on:
      - emqx-core-1
      - emqx-core-2
      - emqx-replicant-1
      - emqx-replicant-2

# 網路配置
networks:
  emqx-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
