apiVersion: v1
kind: Pod
metadata:
  name: gitea-pod
  labels:
    app: gitea
spec:
  containers:
    - name: gitea
      image: docker.io/gitea/gitea:1.26-nightly-rootless
      env:
        # 資料庫設定 (使用 SQLite3)
        - name: GITEA__database__DB_TYPE
          value: sqlite3
        - name: GITEA__database__PATH
          value: /volume/gitea.db
        # 伺服器網址與路徑設定
        - name: GITEA__server__APP_DATA_PATH
          value: /volume/data
        - name: GITEA__server__ROOT_URL
          value: http://localhost:3000/
        # 直接鎖定安裝（跳過 Initial Configuration 網頁）
        - name: GITEA__repository__ROOT
          value: "/volume/repos"
        # 直接鎖定安裝（跳過 Initial Configuration 網頁）
        - name: GITEA__security__INSTALL_LOCK
          value: "true"
      ports:
        - containerPort: 3000
          hostPort: 3000
          protocol: TCP
        - containerPort: 22
          hostPort: 2222
          protocol: TCP
      volumeMounts:
        - mountPath: /volume
          name: gitea-volume
  volumes:
    - name: gitea-volume
      hostPath:
        path: ./gitea-volume
        type: DirectoryOrCreate
