services:
  grafana:
    image: grafana/grafana:12.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./data/conf_bk:/conf_bk
      - ./data/conf/grafana.ini:/etc/grafana/grafana.ini
      # - /etc/letsencrypt:/etc/grafana/letsencrypt
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000/
      - GF_SECURITY_ADMIN_USER=admin
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_AUTH_LDAP_ENABLED=false
      - GF_INSTALL_PLUGINS=tdengine-datasource
