apiVersion: v1
data:
  grafana-datasource.yml: |-
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      url: http://prometheus:9090
      access: proxy
      isDefault: true
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: grafana
  name: grafana-cm1
