version: "3.7"
services:

  haproxy:
    image: haproxy:2.3.9-alpine
    container_name: haproxy
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "10"
    ports:
      - "80:80"
      - "6379:6379"
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"

