version: "3.8"

services:
  zentao:
    image: hub.zentao.net/app/zentao:18.7
    container_name: zentao
    hostname: zentao.lindu-lab.com
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: '1024k'
        max-file: '10'
    environment:
      - MYSQL_INTERNAL=true
    volumes:
      - ./data:/data
    ports:
      - "8082:80"
      - "3306:3306"
